<?php

declare(strict_types=1);

use Illuminate\Support\Str;
use Modules\Notifications\Application\Listeners\QueueConfiguredDomainEventNotification;
use Modules\Notifications\Domain\Models\NotificationTemplate;
use Modules\Scheduling\Domain\Events\ScheduleTimesChanged;
use Modules\Sessions\Domain\Events\SessionScheduled;
use Shared\Testing\Fixtures;

/**
 * تعديل جدول واحد يولّد عشرات الحصص. الإشعار الصحيح ملخّص واحد، لا رسالة عن
 * كل حصة مولّدة — وصل للمعلمة عشرون رسالة عن موعد واحد في 17 سبتمبر 2026.
 */
function configuredEventKeysFor(object $event): array
{
    $listener = app(QueueConfiguredDomainEventNotification::class);
    $method = new ReflectionMethod($listener, 'settingsFor');

    return array_map(
        static fn (array $pair): string => $pair[0],
        $method->invoke($listener, $event, $event->payload()),
    );
}

it('does not notify for a session generated by materialising a schedule', function (): void {
    $event = new SessionScheduled(
        sessionId: (string) Str::ulid(),
        organizationId: Fixtures::organizationId(),
        courseId: (string) Str::ulid(),
        staffProfileId: (string) Str::ulid(),
        scheduledStart: now('UTC')->addDay()->toIso8601String(),
        scheduledEnd: now('UTC')->addDay()->addMinutes(30)->toIso8601String(),
        groupId: null,
        generatedFromSchedule: true,
    );

    expect($event->payload()['generated_from_schedule'])->toBeTrue()
        ->and(configuredEventKeysFor($event))->not->toContain('session.scheduled');
});

it('still notifies for a one-off session that nobody generated from a schedule', function (): void {
    $event = new SessionScheduled(
        sessionId: (string) Str::ulid(),
        organizationId: Fixtures::organizationId(),
        courseId: (string) Str::ulid(),
        staffProfileId: (string) Str::ulid(),
        scheduledStart: now('UTC')->addDay()->toIso8601String(),
        scheduledEnd: now('UTC')->addDay()->addMinutes(30)->toIso8601String(),
        groupId: null,
    );

    expect($event->payload()['generated_from_schedule'])->toBeFalse()
        ->and(configuredEventKeysFor($event))->toContain('session.scheduled');
});

it('announces the new times once when a schedule changes', function (): void {
    $event = new ScheduleTimesChanged(
        scheduleId: (string) Str::ulid(),
        organizationId: Fixtures::organizationId(),
        staffProfileId: (string) Str::ulid(),
        courseId: (string) Str::ulid(),
        rrule: 'FREQ=WEEKLY;INTERVAL=1;BYDAY=MO',
        studentUserIds: ['01TESTSTUDENTUSER00000000'],
        teacherUserId: '01TESTTEACHERUSER00000000',
        courseName: ['ar' => 'كورس', 'en' => 'Course'],
        courseCode: 'C-1',
        targetName: 'طالبة',
        teacherName: 'معلمة',
        durationMinutes: 30,
        sessionCount: 26,
        scheduleTimes: ['2026-11-09 18:30'],
        timezone: 'Europe/Istanbul',
        effectiveFrom: now('UTC')->toIso8601String(),
    );

    expect(configuredEventKeysFor($event))->toBe(['schedule.times_changed']);

    $payload = $event->payload();
    expect($payload['student_user_ids'])->toBe(['01TESTSTUDENTUSER00000000'])
        ->and($payload['teacher_user_id'])->toBe('01TESTTEACHERUSER00000000')
        ->and($payload['session_count'])->toBe(26);
});

it('carries a whatsapp template for the new summary so it cannot fall silent', function (): void {
    $template = NotificationTemplate::query()
        ->whereNull('organization_id')
        ->where('event_key', 'schedule.times_changed')
        ->where('locale', 'ar')
        ->where('channel', 'whatsapp')
        ->first();

    // النص المختصر يذكر النمط الأسبوعي لا كل موعد مولّد — 2026-09-18.
    expect($template)->not->toBeNull()
        ->and((string) $template->body)->toContain('{{weekly_pattern}}')
        ->and((string) $template->body)->not->toContain('{{schedule_times}}');
});

it('keeps a schedule summary on the whatsapp channel', function (): void {
    expect(config('notifications.categories.schedule_summary.channels'))
        ->toContain('whatsapp');
});
